sonar.projectKey=reservasec
sonar.projectName=ReservasEC
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/coverage/**,**/*.min.js,frontend/public/**

sonar.tests=.
sonar.test.inclusions=**/*.test.js,**/*.spec.js,**/*.test.ts,**/*.spec.ts,**/*.test.tsx,**/*.spec.tsx
sonar.test.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**
